  
name: Snowchange_v1

on: workflow_dispatch  
  
jobs:
  Snowchange:
    runs-on: ubuntu-latest
    env:
      SNOWFLAKE_PASSWORD: Dawid32161!
    
    steps:   
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2  
        with:
          python-version: '3.7'
      
      - name: run pip install
        run: | 
          python -m pip install --upgrade pip
          pip install --upgrade snowflake-connector-python
          pip install snowchange
      
      - name: run snowchange
        run: |
          snowchange -f "./snowchange_objects" -a zg95002.eu-central-1 -u dawidsmidoda -r SYSADMIN -w COMPUTE_WH --create-change-history-table
